### ISSUE TITLE
Configuración - TTS opción leer todos los mensajes o usar !speak

### ISSUE THREAD

**Issue by Pythonesa** [chrisvdev/CVTalk#8]
Como usuario
Quiero contar con una opción de configuración que me permita elegir si el TTS lee todos los mensajes o solamente los que se envían utilizando el comando !speak
Para no tener que estar viendo el chat y poder escuchar todos los mensajes cuando quiera

**Comment by chrisvdev** [comment]
Se termino de implementar la funcionalidad con el ultimo Commit -> https://github.com/chrisvdev/CVTalk/commit/b48393668517a9247cc4232d2ec2f074cd099429

Esperamos que la disfrute <3
